version: '2'
services:
  MagnoliaAuthorDB:
    image: mysql:5.7
    environment:
      MYSQL_USER: "MagnoliaAuthor_User"
      MYSQL_PASSWORD: "MagnoliaAuthor_Pass"
      MYSQL_DATABASE: "magnolia"
      MYSQL_ROOT_PASSWORD: "MagnoliaAuthor_Root"
    ports:
      - "3360:3306"
    volumes:
      - /var/lib/docker/volumes/Magnolia/AuthorDB/mysql-5.7:/var/lib/mysql
    labels:
      io.rancher.container.pull_image: always

  MagnoliaPublicDB:
    image: mysql:5.7
    environment:
      MYSQL_USER: "MagnoliaPublic_User"
      MYSQL_PASSWORD: "MagnoliaPublic_Pass"
      MYSQL_DATABASE: "magnolia"
      MYSQL_ROOT_PASSWORD: "MagnoliaPublic_Root"
    ports:
      - "3370:3306"
    volumes:
      - /var/lib/docker/volumes/Magnolia/PublicDB/mysql-5.7:/var/lib/mysql
    labels:
      io.rancher.container.pull_image: always

  MagnoliaAuthorApp:
    image: repositorio-docker.sefaz.al.gov.br/sefaz/sfz-portal-efaz:1.0.0-SNAPSHOT
    command: run
    ports:
      - "3001:8080"
    links:
      - MagnoliaAuthorDB:db
    environment:
      INSTANCE_TYPE: "author"
      DP_TYPE: "mysql"
      DB_ADDRESS: "db"
      DB_PORT: "3360"
      DB_SCHEMA: "magnolia"
      DB_USERNAME: "MagnoliaAuthor_User"
      DB_PASSWORD: "MagnoliaAuthor_Pass"
    volumes:
      - /var/lib/docker/volumes/Magnolia/AuthorApp:/var/lib/tomcat8
    labels:
      io.rancher.container.pull_image: always

  MagnoliaPublicApp:
    image: repositorio-docker.sefaz.al.gov.br/sefaz/sfz-portal-efaz:1.0.0-SNAPSHOT
    command: run
    ports:
      - "3002:8080"
    links:
      - MagnoliaPublicDB:db
    environment:
      INSTANCE_TYPE: "public"
      DP_TYPE: "mysql"
      DB_ADDRESS: "db"
      DB_PORT: "3370"
      DB_SCHEMA: "magnolia"
      DB_USERNAME: "MagnoliaPublic_User"
      DB_PASSWORD: "MagnoliaPublic_Pass"
    volumes:
      - /var/lib/docker/volumes/Magnolia/PublicApp:/var/lib/tomcat8
    labels:
      io.rancher.container.pull_image: always